chore: add release configs
GoogleCloudPlatform/opentelemetry-operations-ruby pull request #12
Opened 2023-06-27 06:52 UTC by NivedhaSenthil

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/GoogleCloudPlatform/opentelemetry-operations-ruby/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea.
- [ ] Follow the instructions in [CONTRIBUTING](CONTRIBUTING.md). Most importantly, ensure the tests and linter pass by running `bundle exec rake ci` in the gem subdirectory.
- [ ] Update code documentation if necessary.

closes: #5

2023-06-28 01:28 UTC, dazuma requested changes

2023-06-28 01:28 UTC, dazuma commented on .github/workflows/release-please.yml
I don't think the release-please and release-please-label workflows will work for a repo in the GoogleCloudPlatform org, because the `YOSHI_CODE_BOT_TOKEN` doesn't exist (possibly among other issues). Drop the workflows and just let the release-please github app do its thing. Use https://github.com/GoogleCloudPlatform/functions-framework-ruby as a model for setting up release automation. In particular, make sure the release-please manifest and config files are set up.

2023-06-28 08:34 UTC, NivedhaSenthil commented on .github/workflows/release-please.yml
Thanks for the pointer @dazuma, have updated to configure release-please app.

2023-07-04 02:48 UTC, dazuma approved these changes
This LGTM, though I understand it's hard to test these things. If it doesn't work, we'll just have to make corrections in a separate pull request.

2023-07-04 03:41 UTC, merged